# Generated by Django 5.2.11 on 2026-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Це акаунт пункту прийому (Партнер)?'),
        ),
    ]
