# Generated by Django 5.2.11 on 2026-03-29 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_transaction_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='Магазин-партнер'),
        ),
        migrations.AddField(
            model_name='userreward',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Використано'),
        ),
        migrations.CreateModel(
            name='StoreOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва винагороди')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('cost', models.IntegerField(verbose_name='Вартість (в балах)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Магазин')),
            ],
        ),
        migrations.AddField(
            model_name='userreward',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_codes', to='main.storeoffer', verbose_name='Яка пропозиція'),
        ),
    ]
